GET http://localhost:3002/api/blogs/60ba4d2b005b4f75d22e6e09
###

POST http://localhost:3002/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJldiIsImlkIjoiNjFhYWNlYWE3YzQ3MWE5ZjlmNjBkODc0IiwiaWF0IjoxNjM4NjAwNzQxfQ.6WwdNfej2RKvdd9ErBpeC__1fv5exOGtSkK8hwp0ZvU

{
   "url": "dhkasdfj.com",
  "title": "Verifies token based authenti",
  "author": "Pratap Singh",
  "likes": 2,
  "userId":"61aaceaa7c471a9f9f60d874"
}

###
DELETE http://localhost:3002/api/users/61a8bf14b5ee7011acf922b2
###
PUT http://localhost:3002/api/blogs/60ba4d2b005b4f75d22e6e09
content-type: application/json

{
     "title": "Sleeping soundly with wrapped in your fist",
  "author": "Sebastian Rathore",
  "likes": 21,
  "url": "jijijiji",
  "userId":"61aaceaa7c471a9f9f60d874"
}

###
POST http://localhost:3002/api/users
content-type: application/json

{
   "username":"rev2",
   "name":"revenants",
   "password":"easy"
}

###
GET http://localhost:3002/api/blogs/

###
POST http://localhost:3002/api/login
content-type: application/json

{
   "username":"rev",
   "password":"easy"
}